-- MySQL Workbench Synchronization
-- Generated: 2018-10-10 21:42
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Наташа

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `mydb`.`Authors` (
  `idAuthor` INT(11) NOT NULL AUTO_INCREMENT,
  `Author_name` VARCHAR(45) NULL DEFAULT NULL,
  `idBook` INT(11) NOT NULL,
  PRIMARY KEY (`idAuthor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `idBook` INT(11) NOT NULL AUTO_INCREMENT,
  `Book_name` VARCHAR(45) NULL DEFAULT NULL,
  `Year_of_publising` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idBook`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
